"""init

Revision ID: e9c3b3ff14d2
Revises: 
Create Date: 2026-09-09 17:36:15.980226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c3b3ff14d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_window_config',
    sa.Column('fire_before_minutes', sa.Integer(), nullable=False),
    sa.Column('expire_after_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_window_config'))
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('admin', 'receptionist', 'doctor', 'head_nurse', 'lab_staff', 'pharmacist', 'patient', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ward', sa.String(length=60), nullable=True),
    sa.Column('patient_profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('doctors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_doctors_department_id_departments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('user_id', name=op.f('uq_doctors_user_id'))
    )
    op.create_table('medicine_formulary',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_dosage', sa.String(length=40), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medicine_formulary')),
    sa.UniqueConstraint('name', name=op.f('uq_medicine_formulary_name'))
    )
    op.create_table('otp_codes',
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_mobile'), 'otp_codes', ['mobile'], unique=False)
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'Other', name='patient_gender'), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_name', sa.String(length=120), nullable=False),
    sa.Column('emergency_phone', sa.String(length=15), nullable=False),
    sa.Column('intake_channel', sa.Enum('emergency', 'phone', 'website', name='intake_channel'), nullable=False),
    sa.Column('profile_status', sa.Enum('draft', 'pending', 'active', 'discharged', 'expired', name='profile_status'), nullable=False),
    sa.Column('admission_type', sa.Enum('inpatient', 'outpatient', 'day_care', name='admission_type'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('medico_legal', sa.Boolean(), nullable=False),
    sa.Column('fir_number', sa.String(length=40), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('ward', sa.String(length=60), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consult_fee', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.Enum('online', 'offline', name='payment_method'), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'link_sent', 'paid', 'deferred', 'waived', name='payment_status'), nullable=False),
    sa.Column('payment_link', sa.String(length=255), nullable=True),
    sa.Column('payment_link_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_number', sa.String(length=40), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_patients_collected_by_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_patients_department_id_departments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_patients_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_mobile'), 'patients', ['mobile'], unique=False)
    op.create_index(op.f('ix_patients_profile_status'), 'patients', ['profile_status'], unique=False)
    op.create_table('specialty_mapping',
    sa.Column('keyword', sa.String(length=120), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialty_mapping'))
    )
    op.create_index(op.f('ix_specialty_mapping_keyword'), 'specialty_mapping', ['keyword'], unique=False)
    op.create_table('stock_items',
    sa.Column('medicine_name', sa.String(length=120), nullable=False),
    sa.Column('batch_number', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_threshold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_expired_flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items'))
    )
    op.create_index(op.f('ix_stock_items_medicine_name'), 'stock_items', ['medicine_name'], unique=False)
    op.create_foreign_key(op.f('fk_users_patient_profile_id_patients'), 'users', 'patients', ['patient_profile_id'], ['id'])
    op.create_table('vitals_config',
    sa.Column('vital_name', sa.String(length=60), nullable=False),
    sa.Column('min_value', sa.DECIMAL(precision=6, scale=1), nullable=False),
    sa.Column('max_value', sa.DECIMAL(precision=6, scale=1), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vitals_config')),
    sa.UniqueConstraint('vital_name', name=op.f('uq_vitals_config_vital_name'))
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('department_fees',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('consult_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_fees_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_fees')),
    sa.UniqueConstraint('department_id', name=op.f('uq_department_fees_department_id'))
    )
    op.create_table('department_specialty',
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_department_specialty_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_specialty'))
    )
    op.create_index(op.f('ix_department_specialty_specialty'), 'department_specialty', ['specialty'], unique=True)
    op.create_table('doctor_roster',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_on_duty', sa.Boolean(), nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_doctor_roster_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_roster')),
    sa.UniqueConstraint('doctor_id', 'day_of_week', name='uq_doctor_roster_doctor_day')
    )
    op.create_table('examination_notes',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_examination_notes_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_examination_notes_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examination_notes'))
    )
    op.create_index(op.f('ix_examination_notes_patient_id'), 'examination_notes', ['patient_id'], unique=False)
    op.create_table('patient_transfers',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('from_doctor_id', sa.UUID(), nullable=False),
    sa.Column('from_dept_id', sa.UUID(), nullable=False),
    sa.Column('transfer_type', sa.Enum('internal', 'external', name='transfer_type'), nullable=False),
    sa.Column('to_dept_id', sa.UUID(), nullable=True),
    sa.Column('to_doctor_id', sa.UUID(), nullable=True),
    sa.Column('to_hospital_name', sa.String(length=120), nullable=True),
    sa.Column('to_hospital_contact', sa.String(length=120), nullable=True),
    sa.Column('urgency', sa.Enum('routine', 'urgent', 'emergency', name='transfer_urgency'), nullable=False),
    sa.Column('transfer_reason', sa.Text(), nullable=False),
    sa.Column('handover_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'completed', 'cancelled', name='transfer_status'), nullable=False),
    sa.Column('decline_count', sa.Integer(), nullable=False),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('admin_approved_by', sa.UUID(), nullable=True),
    sa.Column('discharge_summary_url', sa.String(length=255), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_approved_by'], ['users.id'], name=op.f('fk_patient_transfers_admin_approved_by_users')),
    sa.ForeignKeyConstraint(['from_dept_id'], ['departments.id'], name=op.f('fk_patient_transfers_from_dept_id_departments')),
    sa.ForeignKeyConstraint(['from_doctor_id'], ['doctors.id'], name=op.f('fk_patient_transfers_from_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_transfers_patient_id_patients')),
    sa.ForeignKeyConstraint(['to_dept_id'], ['departments.id'], name=op.f('fk_patient_transfers_to_dept_id_departments')),
    sa.ForeignKeyConstraint(['to_doctor_id'], ['doctors.id'], name=op.f('fk_patient_transfers_to_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_transfers'))
    )
    op.create_index(op.f('ix_patient_transfers_patient_id'), 'patient_transfers', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_transfers_status'), 'patient_transfers', ['status'], unique=False)
    op.create_table('prescriptions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_prescriptions_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_table('test_catalogue',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('tat_min_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('tat_max_hours', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_test_catalogue_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_catalogue'))
    )
    op.create_table('vitals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.DECIMAL(precision=4, scale=1), nullable=True),
    sa.Column('bp_systolic', sa.SmallInteger(), nullable=True),
    sa.Column('bp_diastolic', sa.SmallInteger(), nullable=True),
    sa.Column('pulse_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('spo2_pct', sa.SmallInteger(), nullable=True),
    sa.Column('resp_rate', sa.SmallInteger(), nullable=True),
    sa.Column('blood_glucose', sa.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('gcs_score', sa.SmallInteger(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_vitals_patient_id_patients')),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_vitals_recorded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vitals'))
    )
    op.create_index(op.f('ix_vitals_patient_id'), 'vitals', ['patient_id'], unique=False)
    op.create_table('pharmacy_prescriptions',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'out_of_stock', 'dispensed', name='dispense_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_pharmacy_prescriptions_patient_id_patients')),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_pharmacy_prescriptions_prescription_id_prescriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pharmacy_prescriptions')),
    sa.UniqueConstraint('prescription_id', name=op.f('uq_pharmacy_prescriptions_prescription_id'))
    )
    op.create_index(op.f('ix_pharmacy_prescriptions_patient_id'), 'pharmacy_prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_pharmacy_prescriptions_status'), 'pharmacy_prescriptions', ['status'], unique=False)
    op.create_table('prescription_lines',
    sa.Column('prescription_id', sa.UUID(), nullable=False),
    sa.Column('medicine_name', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=40), nullable=False),
    sa.Column('route', sa.Enum('oral', 'IV', 'IM', 'topical', 'inhalation', name='prescription_route'), nullable=False),
    sa.Column('frequency', sa.Enum('once_daily', 'twice_daily', 'thrice_daily', 'every_6h', 'every_8h', 'as_needed', name='prescription_frequency'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('with_food', sa.Boolean(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], name=op.f('fk_prescription_lines_prescription_id_prescriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_lines'))
    )
    op.create_index(op.f('ix_prescription_lines_prescription_id'), 'prescription_lines', ['prescription_id'], unique=False)
    op.create_table('test_orders',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('test_type_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'reviewed', 'cancelled', name='test_order_status'), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('result_file_url', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_test_orders_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_test_orders_patient_id_patients')),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_catalogue.id'], name=op.f('fk_test_orders_test_type_id_test_catalogue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_orders'))
    )
    op.create_index(op.f('ix_test_orders_patient_id'), 'test_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_test_orders_status'), 'test_orders', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('prescription_line_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('slot_time', sa.Time(), nullable=False),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'FIRED', 'ACKNOWLEDGED', 'GIVEN', 'MISSED', 'CANCELLED', name='alert_status'), nullable=False),
    sa.Column('route_to', sa.Enum('nurse', 'patient_app', name='alert_route_to'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_alerts_patient_id_patients')),
    sa.ForeignKeyConstraint(['prescription_line_id'], ['prescription_lines.id'], name=op.f('fk_alerts_prescription_line_id_prescription_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('prescription_line_id', 'scheduled_date', 'slot_time', name='uq_alert_line_date_slot')
    )
    op.create_index(op.f('ix_alerts_expire_at'), 'alerts', ['expire_at'], unique=False)
    op.create_index(op.f('ix_alerts_fire_at'), 'alerts', ['fire_at'], unique=False)
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_alerts_prescription_line_id'), 'alerts', ['prescription_line_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('dispense_log',
    sa.Column('pharmacy_prescription_id', sa.UUID(), nullable=True),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dispensed_by', sa.UUID(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.id'], name=op.f('fk_dispense_log_dispensed_by_users')),
    sa.ForeignKeyConstraint(['pharmacy_prescription_id'], ['pharmacy_prescriptions.id'], name=op.f('fk_dispense_log_pharmacy_prescription_id_pharmacy_prescriptions')),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_dispense_log_stock_item_id_stock_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispense_log'))
    )
    op.create_table('billing_entries',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dispense_log_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dispense_log_id'], ['dispense_log.id'], name=op.f('fk_billing_entries_dispense_log_id_dispense_log')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_billing_entries_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_entries'))
    )
    op.create_index(op.f('ix_billing_entries_patient_id'), 'billing_entries', ['patient_id'], unique=False)
    op.create_table('medication_log',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('prescription_line_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('administered_by', sa.UUID(), nullable=False),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dose_given', sa.String(length=40), nullable=True),
    sa.Column('route_used', sa.Enum('oral', 'IV', 'IM', 'topical', 'inhalation', name='prescription_route'), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], name=op.f('fk_medication_log_administered_by_users')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_medication_log_alert_id_alerts')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medication_log_patient_id_patients')),
    sa.ForeignKeyConstraint(['prescription_line_id'], ['prescription_lines.id'], name=op.f('fk_medication_log_prescription_line_id_prescription_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_log'))
    )
    op.create_index(op.f('ix_medication_log_patient_id'), 'medication_log', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_log_patient_id'), table_name='medication_log')
    op.drop_table('medication_log')
    op.drop_index(op.f('ix_billing_entries_patient_id'), table_name='billing_entries')
    op.drop_table('billing_entries')
    op.drop_table('dispense_log')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_prescription_line_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_fire_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_expire_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_test_orders_status'), table_name='test_orders')
    op.drop_index(op.f('ix_test_orders_patient_id'), table_name='test_orders')
    op.drop_table('test_orders')
    op.drop_index(op.f('ix_prescription_lines_prescription_id'), table_name='prescription_lines')
    op.drop_table('prescription_lines')
    op.drop_index(op.f('ix_pharmacy_prescriptions_status'), table_name='pharmacy_prescriptions')
    op.drop_index(op.f('ix_pharmacy_prescriptions_patient_id'), table_name='pharmacy_prescriptions')
    op.drop_table('pharmacy_prescriptions')
    op.drop_index(op.f('ix_vitals_patient_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_table('test_catalogue')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_patient_transfers_status'), table_name='patient_transfers')
    op.drop_index(op.f('ix_patient_transfers_patient_id'), table_name='patient_transfers')
    op.drop_table('patient_transfers')
    op.drop_index(op.f('ix_examination_notes_patient_id'), table_name='examination_notes')
    op.drop_table('examination_notes')
    op.drop_table('doctor_roster')
    op.drop_index(op.f('ix_department_specialty_specialty'), table_name='department_specialty')
    op.drop_table('department_specialty')
    op.drop_table('department_fees')
    op.drop_table('audit_log')
    op.drop_table('vitals_config')
    op.drop_index(op.f('ix_stock_items_medicine_name'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_specialty_mapping_keyword'), table_name='specialty_mapping')
    op.drop_table('specialty_mapping')
    op.drop_index(op.f('ix_otp_codes_mobile'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('medicine_formulary')
    op.drop_constraint(op.f('fk_users_patient_profile_id_patients'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_patients_profile_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_mobile'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('departments')
    op.drop_table('alert_window_config')
    # ### end Alembic commands ###
